import { Person } from './player.model';

export const defaultCoaches: Person[] = [
  {
    firstNames: ['Jesús', 'Luis'],
    lastNames: ['Álvarez', 'de', 'Eulate', 'Güergue'],
    firstInitial: 'J',
    singleLastName: 'Álvarez',
    firstNameUsage: 'Spanish',
    lastNameUsage: 'Spanish',
    nationality: 'Andorra',
    age: 52,
    nickname: 'Koldo Álvarez',
    origin: 'Spain',
  },
  {
    firstNames: ['Luc'],
    lastNames: ['Holtz'],
    firstInitial: 'L',
    singleLastName: 'Holtz',
    firstNameUsage: 'French',
    lastNameUsage: 'German',
    nationality: 'Luxembourg',
    age: 53,
    origin: 'Luxembourg',
  },
  {
    firstNames: ['Didier', 'Claude'],
    lastNames: ['Deschamps'],
    firstInitial: 'D',
    singleLastName: 'Deschamps',
    firstNameUsage: 'French',
    lastNameUsage: 'French',
    nationality: 'France',
    age: 54,
    origin: 'France',
  },
  {
    firstNames: ['Jan', 'Olof'],
    lastNames: ['Andersson'],
    firstInitial: 'J',
    singleLastName: 'Andersson',
    firstNameUsage: 'Swedish',
    lastNameUsage: 'Swedish',
    nationality: 'Sweden',
    age: 60,
    origin: 'Sweden',
    nickname: 'Janne Andersson',
  },
  {
    firstNames: ['Gareth'],
    lastNames: ['Southgate'],
    firstInitial: 'G',
    singleLastName: 'Southgate',
    firstNameUsage: 'English (British)',
    lastNameUsage: 'English',
    nationality: 'England',
    age: 52,
    origin: 'England',
  },
  {
    firstNames: ['Markku', 'Tapio'],
    lastNames: ['Kanerva'],
    firstInitial: 'M',
    singleLastName: 'Kanerva',
    firstNameUsage: 'Finnish',
    lastNameUsage: 'Finnish',
    nationality: 'Finland',
    age: 58,
    origin: 'Finland',
  },
  {
    firstNames: ['Zlatko'],
    lastNames: ['Dalić'],
    firstInitial: 'Z',
    singleLastName: 'Dalić',
    firstNameUsage: 'Croatian',
    lastNameUsage: 'Croatian',
    nationality: 'Croatia',
    age: 56,
    origin: 'Croatia',
  },
  {
    firstNames: ['Roberto'],
    lastNames: ['Mancini'],
    firstInitial: 'R',
    singleLastName: 'Mancini',
    firstNameUsage: 'Italian',
    lastNameUsage: 'Italian',
    nationality: 'Italy',
    age: 58,
    origin: 'Italy',
  },
  {
    firstNames: ['Marco'],
    lastNames: ['Rossi'],
    firstInitial: 'M',
    singleLastName: 'Rossi',
    firstNameUsage: 'Italian',
    lastNameUsage: 'Italian',
    nationality: 'Hungary',
    age: 58,
    origin: 'Italy',
  },
  {
    firstNames: ['Julio', 'César'],
    lastNames: ['Ribas', 'Vlacovich'],
    firstInitial: 'J',
    singleLastName: 'Ribas',
    firstNameUsage: 'Spanish',
    lastNameUsage: 'Spanish',
    nationality: 'Gibraltar',
    age: 66,
    origin: 'Uruguay',
    nickname: 'Julio César Ribas',
  },
  {
    firstNames: ['Jaroslav'],
    lastNames: ['Šilhavy'],
    firstInitial: 'J',
    singleLastName: 'Šilhavy',
    firstNameUsage: 'Czech',
    lastNameUsage: 'Czech',
    nationality: 'Czech Republic',
    age: 61,
    origin: 'Czech Republic',
  },
  {
    firstNames: ['Stephen'],
    lastNames: ['Clarke'],
    firstInitial: 'S',
    singleLastName: 'Clarke',
    firstNameUsage: 'English',
    lastNameUsage: 'English',
    nationality: 'Scotland',
    age: 59,
    origin: 'Scotland',
    nickname: 'Steve Clarke',
  },
  {
    firstNames: ['Håkan', 'Georg'],
    lastNames: ['Ericson'],
    firstInitial: 'H',
    singleLastName: 'Ericson',
    firstNameUsage: 'Swedish',
    lastNameUsage: 'Swedish',
    nationality: 'Faroe Islands',
    age: 62,
    origin: 'Sweden',
  },
  {
    firstNames: ['Dainis'],
    lastNames: ['Kazakevičs'],
    firstInitial: 'D',
    singleLastName: 'Kazakevičs',
    firstNameUsage: 'Latvian',
    lastNameUsage: 'Latvian',
    nationality: 'Latvia',
    age: 41,
    origin: 'Latvia',
  },
  {
    firstNames: ['Stephen'],
    lastNames: ['Kenny'],
    firstInitial: 'S',
    singleLastName: 'Kenny',
    firstNameUsage: 'English',
    lastNameUsage: 'Irish',
    nationality: 'Ireland',
    age: 51,
    origin: 'Ireland',
  },
  {
    firstNames: ['Kasper'],
    lastNames: ['Hjulmand'],
    firstInitial: 'K',
    singleLastName: 'Hjulmand',
    firstNameUsage: 'Danish',
    lastNameUsage: 'Danish',
    nationality: 'Denmark',
    age: 50,
    origin: 'Denmark',
  },
  {
    firstNames: ['Giovanni'],
    lastNames: ['De Biasi'],
    firstInitial: 'G',
    singleLastName: 'De Biasi',
    firstNameUsage: 'Italian',
    lastNameUsage: 'Italian',
    nationality: 'Azerbaijan',
    age: 66,
    origin: 'Italy',
    nickname: 'Gianni De Biasi',
  },
  {
    firstNames: ['Martin'],
    lastNames: ['Stocklasa'],
    firstInitial: 'M',
    singleLastName: 'Stocklasa',
    firstNameUsage: 'Liechtenstein',
    lastNameUsage: 'Liechtenstein',
    nationality: 'Liechtenstein',
    age: 43,
    origin: 'Liechtenstein',
  },
  {
    firstNames: ['Ståle'],
    lastNames: ['Solbakken'],
    firstInitial: 'S',
    singleLastName: 'Solbakken',
    firstNameUsage: 'Norwegian',
    lastNameUsage: 'Norwegian',
    nationality: 'Norway',
    age: 54,
    origin: 'Norway',
  },
  {
    firstNames: ['Arnar', 'Þór'],
    lastNames: ['Viðarsson'],
    firstInitial: 'A',
    singleLastName: 'Viðarsson',
    firstNameUsage: 'Icelandic',
    lastNameUsage: 'Icelandic',
    nationality: 'Iceland',
    age: 44,
    origin: 'Iceland',
  },
  {
    firstNames: ['Miodrag'],
    lastNames: ['Radulović'],
    firstInitial: 'M',
    singleLastName: 'Radulović',
    firstNameUsage: 'Serbian',
    lastNameUsage: 'Serbian',
    nationality: 'Montenegro',
    age: 55,
    origin: 'Montenegro',
  },
  {
    firstNames: ['Thomas'],
    lastNames: ['Häberli'],
    firstInitial: 'T',
    singleLastName: 'Häberli',
    firstNameUsage: 'English',
    lastNameUsage: 'Swiss',
    nationality: 'Estonia',
    age: 48,
    origin: 'Switzerland',
  },
  {
    firstNames: ['Willy', 'David', 'Frédéric'],
    lastNames: ['Sagnol'],
    firstInitial: 'W',
    singleLastName: 'Sagnol',
    firstNameUsage: 'French',
    lastNameUsage: 'French',
    nationality: 'Estonia',
    age: 45,
    origin: 'Georgia',
  },
  {
    firstNames: ['Dragan'],
    lastNames: ['Stojković'],
    firstInitial: 'D',
    singleLastName: 'Stojković',
    firstNameUsage: 'Serbian',
    lastNameUsage: 'Serb',
    nationality: 'Serbia',
    age: 48,
    origin: 'Serbia',
  },
];
